version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hk-stock-client
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - traefik
    ports:
      - "3456:3456"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hk-stock-client.rule=Host(`tfipc.subx.fun`)"
      - "traefik.http.routers.hk-stock-client.entrypoints=websecure"
      - "traefik.http.routers.hk-stock-client.tls.certresolver=letsencrypt"
      - "traefik.http.services.hk-stock-client.loadbalancer.server.port=3456"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
